### PR TITLE
feat: revert changed vertical alignment of title frame

### PR DESCRIPTION
**Pull request by jpcirrus**
8f2a59e replaced `\vfill` with `\vfil` in the title page minipage but this lowered the vertical alignment of the minipage contents. This commit reverts the vertical alignment to what it was previously.

### CODE REVIEW

**Comment by jpcirrus** [comment]
However, there remains the issue of the contents of both the title page and section page minipages being closer to the top of their respective frames than being centered.

**Comment by jolars** [comment]
Thanks for the PR. I'll take a look at this later today.

**Comment by jolars** [comment]
I don't know... I think the new title page looks fine for a title page with an image, but when there is no titlegraphic I think it looks better to have it off-centered towards the bottom. Not sure I can motivate it, it just looks that way to me.

Here is a comparison. Before the PR on the left and after on the right.

tmp

Perhaps the margin to the bottom should be fixed instead. I'm not sure what's best here really.

**Comment by jpcirrus** [comment]
Just seen #31. Should this PR rather be closed in favour of the flexibility of that proposal?

When the title page has a titlegraphic, absolute centering is accomplished with:

```latex
\setbeamertemplate{title page}{
  \begin{minipage}{\textwidth}
    \ifx\inserttitlegraphic\@empty\else\usebeamertemplate*{title graphic}\fi
    \ifx\inserttitle\@empty\else\usebeamertemplate*{title}\fi
    \ifx\insertsubtitle\@empty\else\usebeamertemplate*{subtitle}\fi
    \usebeamertemplate*{title separator}
    \expandafter\ifblank\expandafter{\beamer@andstripped}{}{%
      \usebeamertemplate*{author}%
    }
    \ifx\insertinstitute\@empty\else\usebeamertemplate*{institute}\fi
    \ifx\insertdate\@empty\else\usebeamertemplate*{date}\fi
  \end{minipage}%
}
```

but for reasons I haven't been able to discover, without a titlegraphic that code results in the contents being slightly raised above center.

**Comment by jolars** [comment]
> Just seen #31. Should this PR rather be closed in favour of the flexibility of that proposal?
> 
> When the title page has a titlegraphic, absolute centering is accomplished with:
> 
> ```
> \setbeamertemplate{title page}{
>   \begin{minipage}{\textwidth}
>     \ifx\inserttitlegraphic\@empty\else\usebeamertemplate*{title graphic}\fi
>     \ifx\inserttitle\@empty\else\usebeamertemplate*{title}\fi
>     \ifx\insertsubtitle\@empty\else\usebeamertemplate*{subtitle}\fi
>     \usebeamertemplate*{title separator}
>     \expandafter\ifblank\expandafter{\beamer@andstripped}{}{%
>       \usebeamertemplate*{author}%
>     }
>     \ifx\insertinstitute\@empty\else\usebeamertemplate*{institute}\fi
>     \ifx\insertdate\@empty\else\usebeamertemplate*{date}\fi
>   \end{minipage}%
> }
> ```
> 
> but for reasons I haven't been able to discover, without a titlegraphic that code results in the contents being slightly raised above center.

Yes, maybe so. Although there might be reason to look into the current, default one, as well. Thanks for the example. A simple centered version of the default seems like a good and easy alternative to have.

**Comment by jolars** [comment]
I made a small change to the default now, which gives slightly more predictable results I think. Part of the problem was the alignment of the mini page, which caused it to be shifted downwards. One possibility going forward is to make the spacing command for the top and bottom of the title page an option, which should enable anyone to transparently get whatever alignment they want. Or there could be a couple of predefined options. Maybe just having an option to center it would suffice.

**Pull request closed without merging**
